version: '3.7'
services:
    ui:
      build: 
        context: /home/hrvwnd/Documents/git/QA-Portal/qa-portal-angular
        dockerfile: Dockerfile
      volumes:
      - type: bind
        source: ../qa-portal-angular/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
        - target: 80
          published: 80
          protocol: tcp