version: '3.7'
services:

    mongo:
      image: mongo
      environment:
      - MONGO_INITDB_DATABASE=qa-portal
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      volumes:
      - ./mongo-data:/data/db
      ports:
      - 27019:27017