version: '3.7'
services:  

    postgres:
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=qa-portal
      volumes:
        - db-data:/var/lib/postgresql/data/
      ports:
        - "5434:5432"

    mongo:
      image: mongo
      environment:
      - MONGO_INITDB_DATABASE=qa-portal
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      volumes:
      - ./mongo-data:/data/db
      ports:
      - 27019:27017

    ui:
      image: shaybs/ui:${BUILD_NUMBER}
      build: 
        context: ./../qa-portal-angular
        dockerfile: Dockerfile
      volumes:
      - type: bind
        source: ../qa-portal-angular/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
        - target: 80
          published: 80
          protocol: tcp  

    portal-app-api:
      image: shaybs/portal-app-api:${BUILD_NUMBER}
      build: 
        context: ./
        args: 
          - PROJECT=portal-application-api
        dockerfile: Dockerfile
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
      - POSTGRES_HOST=postgres
      - ENABLE_PUBLIC_ENDPOINTS=true
      depends_on:
      - postgres

    cohort-api:
      image: shaybs/cohort-api:${BUILD_NUMBER}
      build: 
        context: ./
        args: 
          - PROJECT=cohort-api
        dockerfile: Dockerfile
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
      - POSTGRES_HOST=postgres
      - ENABLE_PUBLIC_ENDPOINTS=true
      depends_on:
      - postgres

    cv-api:
      image: shaybs/cv-api:${BUILD_NUMBER}
      build: 
        context: ./
        args: 
          - PROJECT=cv-api
        dockerfile: Dockerfile
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
      - POSTGRES_HOST=postgres
      - ENABLE_PUBLIC_ENDPOINTS=true
      depends_on:
      - postgres
      - mongo
      
    feedback-api:
      image: shaybs/feedback-api:${BUILD_NUMBER}
      build: 
        context: ./
        args: 
          - PROJECT=feedback-api
        dockerfile: Dockerfile
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
      - POSTGRES_HOST=postgres
      - ENABLE_PUBLIC_ENDPOINTS=true
      depends_on:
      - postgres
      
    form-api:
      image: shaybs/form-api:${BUILD_NUMBER}
      build: 
        context: ./
        args: 
          - PROJECT=form-api
        dockerfile: Dockerfile
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
      - POSTGRES_HOST=postgres
      - ENABLE_PUBLIC_ENDPOINTS=true
      depends_on:
      - postgres
      
    self-reflection-api:
      image: shaybs/self-reflection-api:${BUILD_NUMBER}
      build: 
        context: .
        args: 
          - PROJECT=self-reflection-api
        dockerfile: Dockerfile
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-portal
      - POSTGRES_HOST=postgres
      - ENABLE_PUBLIC_ENDPOINTS=true
      depends_on:
      - postgres

volumes:
  db-data:
  mongo-data:      
